config/routes.rb
Rails.application.routes.draw do
  resources :brands
  resources :locations

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post '/create_csv', to: 'pages#create_csv'
  post '/kill_jobs', to: 'pages#kill_jobs'
  post '/sku_csv', to: 'pages#sku_csv'
  post '/check_sku', to: 'inventory_items#check_sku'
  get  'pages/index', to: 'pages#index'
  get '/login', to: 'sessions#login'
  get '/logout', to: 'sessions#logout'
  post '/confirm_login', to: 'sessions#confirm_login'
  post 'inventory_items/mass_action', to: 'inventory_items#mass_action'
  get 'inventory_items/destroy_all', :to => 'inventory_items#destroy_all'
  get 'inventory_items/soft_deleted', to: 'inventory_items#soft_deleted'
  post 'inventory_items/recover/:id', to: 'inventory_items#recover'
  post 'team_player_designs/mass_delete', to: 'team_player_designs#mass_delete'
  post 'team_players/mass_delete', to: 'team_players#mass_delete'
  post 'clothing/mass_toggle', to: 'clothing#mass_toggle'
  post 'accessory/mass_toggle', to: 'accessory#mass_toggle'

  resources :sales_channels
  resources :colors
  resources :teams do
    resources :team_players, only: :index
  end
  resources :team_players, only: [:show, :edit, :update, :destroy]
  resources :sizes
  resources :royalties
  resources :reserved_designs
  resources :team_player_designs
  resources :inventory_items do
    member do
      post 'recover'
    end
  end

  resources :clothing do
    get '/clothing_colors', to: 'clothing_colors#edit'
    put '/clothing_colors', to: 'clothing_colors#update'
    get '/clothing_sizes', to: 'clothing_sizes#edit'
    put '/clothing_sizes', to: 'clothing_sizes#update'
    post 'toggle_active', to: 'clothing#toggle_active'
    resources :tags
  end

  resources :accessory do
    get '/accessory_colors', to: 'accessory_colors#edit'
    put '/accessory_colors', to: 'accessory_colors#update'
    get '/accessory_sizes', to: 'accessory_sizes#edit'
    put '/accessory_sizes', to: 'accessory_sizes#update'
    post 'toggle_active', to: 'accessory#toggle_active'
    resources :tags
  end

  root to: 'sessions#login'
end

app/models/reserved_design.rb
class ReservedDesign < ApplicationRecord
  validates_presence_of :artist, :snippet
  before_create :generate_sku
  before_validation :standardize_fields
  validate :minimum_sku
  validates_uniqueness_of :design_sku

  private

  def minimum_sku
    if design_sku && design_sku < ENV['MINIMUM_SKU'].to_i
      self.errors.add(:design_sku, "must be greater than or equal to #{ENV['MINIMUM_SKU']}")
    end
  end

  def standardize_fields
    self.artist = self.artist.downcase
    self.snippet = self.snippet.downcase
  end

  def generate_sku
    unless design_sku
      possible_ids = (ENV['MINIMUM_SKU'].to_i..99).to_a
      used_ids = ReservedDesign.pluck(:design_sku)
      self.design_sku = (possible_ids - used_ids).first
    end
  end
end

app/controllers/reserved_designs_controller.rb
class ReservedDesignsController < ApplicationController
  def index
    @reserved_designs = ReservedDesign.all
  end

  def new
    @reserved_design = ReservedDesign.new
  end

  def edit
    @reserved_design = ReservedDesign.find(params[:id])
  end

  def create
    @reserved_design = ReservedDesign.new(design_params)

    if @reserved_design.save
      flash[:notice] = "Reserved Design Saved with SKU #{@reserved_design.design_sku}"
      redirect_to reserved_designs_path
    else
      flash[:error] = "Reserved Design Not Saved"
      render :new
    end
  end

  def update
    @reserved_design = ReservedDesign.find(params[:id])
    if @reserved_design.update_attributes(design_params)
      flash[:notice] = "Reserved Design Updated"
      redirect_to reserved_designs_path
    else
      flash[:error] = "Reserved Design Not Updated"
      render :edit
    end
  end

  private 

  def design_params
    params.require(:reserved_design).permit(:artist, :snippet, :design_sku)
  end
end

app/views/reserved_designs/_form.html.slim
- if @reserved_design.errors.any?
  | #{@reserved_design.errors.full_messages.to_sentence}
.long-fieldset
  = f.label :artist
  = f.text_field :artist
.long-fieldset
  = f.label :snippet, 'Design Snippet'
  = f.text_field :snippet
.long-fieldset
  = f.label :design_sku, "SKU (optional: minimum #{ENV['MINIMUM_SKU']})"
  = f.number_field :design_sku
.fieldset
  = f.submit

app/views/reserved_designs/edit.html.slim
h1 Edit Reserved Design

= form_for @reserved_design do |f|
  - render partial: 'form', locals: { f: f }

app/views/reserved_designs/index.html.slim
h1 Reserved Designs

p
  = link_to 'New Reserved Design', new_reserved_design_path

- if @reserved_designs.any?
  table
    tr
      td Artist
      td Design Name
      td Design Sku
      - @reserved_designs.each do |design|
        tr
          td = design.artist.titleize
          td = design.snippet.titleize
          td = design.design_sku
          td = link_to 'Edit', edit_reserved_design_path(design)
- else
    | No Reserved Designs Exist

app/views/reserved_designs/new.html.slim
h1 New Reserved Design

= form_for @reserved_design do |f|
  - render partial: 'form', locals: { f: f }