config/routes.rb
Rails.application.routes.draw do
  resources :brands
  resources :locations

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post '/create_csv', to: 'pages#create_csv'
  post '/kill_jobs', to: 'pages#kill_jobs'
  post '/sku_csv', to: 'pages#sku_csv'
  post '/check_sku', to: 'inventory_items#check_sku'
  get  'pages/index', to: 'pages#index'
  get '/login', to: 'sessions#login'
  get '/logout', to: 'sessions#logout'
  post '/confirm_login', to: 'sessions#confirm_login'
  post 'inventory_items/mass_action', to: 'inventory_items#mass_action'
  get 'inventory_items/destroy_all', :to => 'inventory_items#destroy_all'
  get 'inventory_items/soft_deleted', to: 'inventory_items#soft_deleted'
  post 'inventory_items/recover/:id', to: 'inventory_items#recover'
  post 'team_player_designs/mass_delete', to: 'team_player_designs#mass_delete'
  post 'team_players/mass_delete', to: 'team_players#mass_delete'
  post 'clothing/mass_toggle', to: 'clothing#mass_toggle'
  post 'accessory/mass_toggle', to: 'accessory#mass_toggle'

  resources :sales_channels
  resources :colors
  resources :teams do
    resources :team_players, only: :index
  end
  resources :team_players, only: [:show, :edit, :update, :destroy]
  resources :sizes
  resources :royalties
  resources :reserved_designs
  resources :team_player_designs
  resources :inventory_items do
    member do
      post 'recover'
    end
  end

  resources :clothing do
    get '/clothing_colors', to: 'clothing_colors#edit'
    put '/clothing_colors', to: 'clothing_colors#update'
    get '/clothing_sizes', to: 'clothing_sizes#edit'
    put '/clothing_sizes', to: 'clothing_sizes#update'
    post 'toggle_active', to: 'clothing#toggle_active'
    resources :tags
  end

  resources :accessory do
    get '/accessory_colors', to: 'accessory_colors#edit'
    put '/accessory_colors', to: 'accessory_colors#update'
    get '/accessory_sizes', to: 'accessory_sizes#edit'
    put '/accessory_sizes', to: 'accessory_sizes#update'
    post 'toggle_active', to: 'accessory#toggle_active'
    resources :tags
  end

  root to: 'sessions#login'
end

app/models/inventory_item.rb
class InventoryItem < ApplicationRecord
  belongs_to :team_player_design
  belongs_to :team_player
  belongs_to :size
  belongs_to :color
  belongs_to :producible, -> { unscope(where: :active) }, polymorphic: true

  attr_accessor :bulk_csv
  validates_presence_of :full_sku
  validates_uniqueness_of :full_sku
  acts_as_paranoid

  def build_entry
    return false unless check_data
    row = { 'Title' => team_player_design.name.split.map(&:capitalize).join(' '), 'Team' => team_player.team.name, 'Player' => team_player.player, 'League' => team_player.team.league, 'City' => team_player.team.city, 'Artist' => team_player_design.artist.split.map(&:capitalize).join(' ') }
    begin
      entry = InputEntry.new(row)
    rescue NoMethodError
      return false
    end
    entry
  end

  def check_data
    return false if team_player_design == nil || team_player == nil || size == nil || color == nil || producible == nil || team_player.team == nil
    true
  end

  def add_quantity(line)
    line[0][16] = quantity
    return line
  end

  def self.build_leagues_and_teams(items)
    leagues_and_teams = []
    items.each do |item|
      if item.team_player != nil && item.team_player.team != nil
        leagues_and_teams  <<  [item.team_player.team.league, item.team_player.team.name]
      end
    end
    leagues_and_teams.uniq!
    leagues_and_teams
  end

end

app/controllers/inventory_items_controller.rb
class InventoryItemsController < ApplicationController
  helper_method :sort_column, :sort_direction

  def index
    @inventory_items = InventoryItem.all.order(sort_data + " " + sort_direction).includes(:team_player_design, :color, :size, team_player: [:team])
  end

  def new
    @inventory_item = InventoryItem.new
    @locations = Location.all
  end

  def edit
    @inventory_item = InventoryItem.find(params[:id])
    @locations = Location.all
  end

  def update
    @inventory_item = InventoryItem.find(params[:id])
    full_sku = item_params[:full_sku]
    @inventory_item.full_sku = full_sku
    @inventory_item.location = item_params[:location]
    @team = Team.where(id: full_sku.slice(15..18)).first
    @player = @team.team_players.where(sku: full_sku.slice(20..22)).first
    @design = TeamPlayerDesign.where(sku: full_sku.slice(24..25).to_i, team_player_id: @player.id).first
    @inventory_item.team_player_id = @player.id
    @inventory_item.team_player_design_id = @design.id
    @inventory_item.color_id = Color.where(sku: full_sku.slice(8..10)).first.id
    @inventory_item.size_id = Size.where(sku: full_sku.slice(3..4)).first.id
    @item = Accessory.unscoped.where(sku: full_sku.slice(5..7)).first || Clothing.unscoped.where(sku: full_sku.slice(5..7)).first
    @inventory_item.producible_id = @item.id
    @inventory_item.producible_type = @item.class.name  
    @inventory_item.product = @item.style
    if @inventory_item.save
      flash[:notice] = 'Inventory Item updated'
      redirect_to inventory_items_path
    else
      flash[:error] = 'Inventory Item was not updated'
      render :edit
    end
  end

  def create
    if !params[:bulk_sku].blank?
      bulk_sku_path = Uploader.call(params[:bulk_sku].path)
      InventoryUploadJob.perform_later(bulk_sku_path)
      flash[:notice] = "Bulk inventory uploads are being processed"
    else
      @inventory_item = InventoryItem.new
      full_sku = item_params[:full_sku]
      @inventory_item.full_sku = full_sku
      @inventory_item.location = item_params[:location]
      @team = Team.where(id: full_sku.slice(15..18)).first
      @player = @team.team_players.where(sku: full_sku.slice(20..22)).first
      @design = TeamPlayerDesign.where(sku: full_sku.slice(24..25).to_i, team_player_id: @player.id).first
      @inventory_item.team_player_id = @player.id
      @inventory_item.team_player_design_id = @design.id
      @inventory_item.color_id = Color.where(sku: full_sku.slice(8..10)).first.id
      @inventory_item.size_id = Size.where(sku: full_sku.slice(3..4)).first.id
      @item = Accessory.unscoped.where(sku: full_sku.slice(5..7)).first || Clothing.unscoped.where(sku: full_sku.slice(5..7)).first
      @inventory_item.producible_id = @item.id
      @inventory_item.producible_type = @item.class.name  
      @inventory_item.product = @item.style
      if @inventory_item.save
        flash[:notice] = "Inventory Item Saved"
      else
        @existing_item = InventoryItem.where(full_sku: @inventory_item.full_sku).first
        if @existing_item
          @existing_item.update_attributes(quantity: @existing_item.quantity + 1)
          flash[:notice] = "Item quantity increased"
        else
          flash[:error] = "Inventory Item Not Saved"
        end
      end
    end
    redirect_to inventory_items_path
  end

  def check_sku
    if !params[:sku_csv].blank?
      uploaded_sku_path = Uploader.call(params[:sku_csv].path)
      CheckSkuJob.perform_later(User.find(session[:user_id]).email,
                                 uploaded_sku_path)
      flash[:notice] = "An email with CSV attached will be sent soon"
    else
      flash[:error] = "Input File File Required"
    end
    redirect_to inventory_items_path
  end

  def destroy
    @inventory_item = InventoryItem.find(params[:id])
    if @inventory_item.destroy!
      flash[:notice] = 'Item Deleted'
    else
      flash[:error] = 'Item Not Deleted'
    end

    redirect_to inventory_items_path
  end

  def destroy_all
    @inventory_items = InventoryItem.only_deleted
    @size = @inventory_items.size
    if @inventory_items.delete_all!
      flash[:notice] = "#{@size} Items Deleted"
    else
      flash[:error] = 'Items Not Deleted'
    end
    redirect_to inventory_items_path
  end


  def mass_action
    if params['commit'] == 'Delete Items'
      @inventory_items = InventoryItem.where(id: params['inventory_item_ids'])
      @size = @inventory_items.size
      if @inventory_items.delete_all
        flash[:notice] = "#{@size} Items Deleted"
      else
        flash[:error] = 'Items Not Deleted'
      end
    else
      inventory_item_ids = params['inventory_item_ids']
      ClearanceCsvJob.perform_later(User.find(session[:user_id]).email,
                                 inventory_item_ids)
      flash[:notice] = "An email with CSV attached will be sent soon"
    end
    redirect_to inventory_items_path
  end

  def soft_deleted
    @inventory_items = InventoryItem.only_deleted
  end

  def recover
    @inventory_item = InventoryItem.only_deleted.find(params[:id])
    if @inventory_item.recover
      flash[:notice] = "Inventory Item Recovered"
      redirect_to inventory_items_path
    else
      flash[:error] = "Inventory Item Not Recovered"
      redirect_to inventory_items_path
    end
  end



  private

  def item_params
    params.require(:inventory_item).permit(:full_sku, :location, :quantity, :bulk_sku)
  end

  def sort_data
    if params[:sort] == "design"
      "team_player_designs.name"
    elsif params[:sort] == "player"
      "team_players.player"
    elsif params[:sort] == "size"
      "sizes.name"
    elsif params[:sort] == "color"
      "colors.name"
    elsif params[:sort] == "league"
      "teams.league"
    elsif params[:sort] == "team"
      "teams.name"
    elsif params[:sort] == "product"
      "product"
    elsif params[:sort] == "location"
      "location"
    elsif params[:sort] == "quantity"
      "quantity"
    elsif params[:sort] == "date_added"
      "created_at"
    elsif params[:sort] == "full_sku"
      "full_sku"
    else
      "team_player_id"
    end
  end

  def sort_column
    %w[design team player league product size color location quantity date_added full_sku].include?(params[:sort]) ? params[:sort] : "team_player_id"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

end

app/views/inventory_items/edit.html.slim
= form_for @inventory_item do |f|
  .fieldset
    = f.label :SKU
    = f.text_field :full_sku
  .fieldset
    = f.label :Location
    = f.select "location", options_for_select(@locations.collect{ |u| [u.name, u.name] })
  .fieldset
    = f.label :Quantity
    = f.number_field :quantity
  = f.submit

= form_tag new_inventory_item_path, multipart: true, id: 'sku_upload' do |f|
  h4 Upload SKU CSV
  .fieldset
    = label_tag :sku_csv
    = file_field_tag :sku_csv
  = submit_tag "Check SKUs"

app/views/inventory_items/index.html.slim
= link_to 'New Inventory Item', new_inventory_item_path
= form_tag check_sku_path, multipart: true, id: 'sku_upload' do |f|
  h4 Upload SKU CSV
  .fieldset
    = label_tag :sku_csv
    = file_field_tag :sku_csv
  = submit_tag "Check SKUs"

h4 Manage Inventory Items

= form_tag inventory_items_mass_action_path do |f|
  = submit_tag 'Delete Items'
  br
  = submit_tag 'Clearance CSV'
  br
  = link_to "Undo Delete", inventory_items_soft_deleted_path
  table
    tr
      th
      th 
        = sortable "full_sku" 
      th 
        = sortable "product"
      th 
        = sortable "design"
      th 
        = sortable "team"
      th 
        = sortable "player"
      th 
        = sortable "league"
      th 
        = sortable "size"
      th 
        = sortable "color"
      th 
        = sortable "location"
      th 
        = sortable "quantity"
      th 
        = sortable "date_added"

    tr
      td = check_box_tag 'inactive_accessory_check', nil, checked = false, class: 'inventoryItemCheck'
      td Select All
    - @inventory_items.each do |item|
      tr
        td = check_box_tag 'inventory_item_ids[]', item.id, checked = false, class: "inventoryItem"
        td = item.full_sku
        td = item.product
        td = item.team_player_design.name if item.team_player_design
        td = item.team_player.team.name if item.team_player
        td = item.team_player.player if item.team_player
        td = item.team_player.team.league if item.team_player
        td = item.size.name if item.size
        td = item.color.name if item.color
        td = item.location
        td = item.quantity
        td = item.created_at.strftime('%D')
        td = link_to "Edit", edit_inventory_item_path(item)

app/views/inventory_items/new.html.slim
= form_for @inventory_item, :html => { :multipart => true } do |f|
  h4 Single Item
  .fieldset
    = f.label :SKU
    = f.text_field :full_sku
  .fieldset
    = f.label :Location
    = f.select "location", options_for_select(@locations.collect{ |u| [u.name, u.name] })
  .fieldset
    = f.label :Quantity
    = f.number_field :quantity
  .fieldset
    = label_tag :bulk_csv
    = file_field_tag :bulk_sku
  = f.submit

= link_to "Manage Locations", locations_path

app/views/inventory_items/soft_deleted.html.slim
h4 Manage Inventory Items

= link_to "Clear deleted items", inventory_items_destroy_all_path

table
  tr
    th Full Sku 
    th 
      = sortable "product"
    th 
      = sortable "design"
    th 
      = sortable "team"
    th 
      = sortable "player"
    th 
      = sortable "league"
    th Size
    th Color
    th Location
    th Quantity
    th Date Added
    th


  - @inventory_items.each do |item|
    tr
      td = item.full_sku
      td = item.product
      td = item.team_player_design.name if item.team_player_design
      td = item.team_player.team.name if item.team_player
      td = item.team_player.player if item.team_player
      td = item.team_player.team.league if item.team_player
      td = item.size.name if item.size
      td = item.color.name if item.color
      td = item.location
      td = item.quantity
      td = item.created_at.strftime('%D')
      td = form_tag recover_inventory_item_path(item), method: 'POST', data: { confirm: "This will undelete #{item.product}" }
        = submit_tag "Undelete"