config/routes.rb
Rails.application.routes.draw do
  resources :brands
  resources :locations

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post '/create_csv', to: 'pages#create_csv'
  post '/kill_jobs', to: 'pages#kill_jobs'
  post '/sku_csv', to: 'pages#sku_csv'
  post '/check_sku', to: 'inventory_items#check_sku'
  get  'pages/index', to: 'pages#index'
  get '/login', to: 'sessions#login'
  get '/logout', to: 'sessions#logout'
  post '/confirm_login', to: 'sessions#confirm_login'
  post 'inventory_items/mass_action', to: 'inventory_items#mass_action'
  get 'inventory_items/destroy_all', :to => 'inventory_items#destroy_all'
  get 'inventory_items/soft_deleted', to: 'inventory_items#soft_deleted'
  post 'inventory_items/recover/:id', to: 'inventory_items#recover'
  post 'team_player_designs/mass_delete', to: 'team_player_designs#mass_delete'
  post 'team_players/mass_delete', to: 'team_players#mass_delete'
  post 'clothing/mass_toggle', to: 'clothing#mass_toggle'
  post 'accessory/mass_toggle', to: 'accessory#mass_toggle'

  resources :sales_channels
  resources :colors
  resources :teams do
    resources :team_players, only: :index
  end
  resources :team_players, only: [:show, :edit, :update, :destroy]
  resources :sizes
  resources :royalties
  resources :reserved_designs
  resources :team_player_designs
  resources :inventory_items do
    member do
      post 'recover'
    end
  end

  resources :clothing do
    get '/clothing_colors', to: 'clothing_colors#edit'
    put '/clothing_colors', to: 'clothing_colors#update'
    get '/clothing_sizes', to: 'clothing_sizes#edit'
    put '/clothing_sizes', to: 'clothing_sizes#update'
    post 'toggle_active', to: 'clothing#toggle_active'
    resources :tags
  end

  resources :accessory do
    get '/accessory_colors', to: 'accessory_colors#edit'
    put '/accessory_colors', to: 'accessory_colors#update'
    get '/accessory_sizes', to: 'accessory_sizes#edit'
    put '/accessory_sizes', to: 'accessory_sizes#update'
    post 'toggle_active', to: 'accessory#toggle_active'
    resources :tags
  end

  root to: 'sessions#login'
end

app/models/royalty.rb
class Royalty < ApplicationRecord
  validates_presence_of :code, :league
  validates_uniqueness_of :code, :league

  before_validation :set_fields

  private

  def set_fields
    self.code = code.upcase
  end
end

app/controllers/royalties_controller.rb
class RoyaltiesController < ApplicationController
  def index
    @royalties = Royalty.order(:code)
  end

  def new
    @royalty = Royalty.new
  end

  def edit
    @royalty = Royalty.find(params[:id])
  end

  def update
    @royalty = Royalty.find(params[:id])

    if @royalty.update_attributes(royalty_params)
      flash[:notice] = "Royalty Updated"
      redirect_to royalties_path
    else
      flash[:error] = "Royalty Not Updated"
      render :edit
    end
  end

  def create
    @royalty = Royalty.new(royalty_params)

    if @royalty.save
      flash[:notice] = "Royalty Saved"
      redirect_to royalties_path
    else
      flash[:error] = "Royalty Not Saved"
      render :new
    end
  end

  def destroy
    @royalty = Royalty.find(params[:id])
    if @royalty.destroy
      flash[:notice] = 'Royalty deleted'
    else
      flash[:error] = 'Royalty not deleted'
    end
    redirect_to royalties_path
  end

  private

  def royalty_params
    params.require(:royalty).permit(:code, :percentage, :league)
  end
end

app/views/royalties/_form.html.slim
.fieldset
  = f.label :code
  = f.text_field :code
.fieldset
  = f.label :league
  = f.text_field :league
.fieldset
  = f.label :percentage
  = f.number_field :percentage, step: 0.5
= f.submit

app/views/royalties/edit.html.slim
h1 Edit Royalty

= form_for @royalty do |f|
  = render partial: 'form', locals: { f: f }

app/views/royalties/index.html.slim
h1 Royalties
= link_to 'New Royalty', new_royalty_path
table
  tr
    th Code
    th League
    th Percentage (%)
    - if @royalties.any?
      - @royalties.each do |royalty|
        tr
          td = royalty.code
          td = royalty.league
          td = royalty.percentage
          td = link_to 'Edit', edit_royalty_path(royalty)
          td = form_tag royalty_path(royalty), method: 'DELETE', data: { confirm: "This will delete #{royalty.league} for all designs" }
            = submit_tag "Delete"
    - else
      tr
        td No Royalties Available

app/views/royalties/new.html.slim
h1 New Royalty

= form_for @royalty do |f|
  = render partial: 'form', locals: { f: f }