config/routes.rb
Rails.application.routes.draw do
  resources :brands
  resources :locations

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post '/create_csv', to: 'pages#create_csv'
  post '/kill_jobs', to: 'pages#kill_jobs'
  post '/sku_csv', to: 'pages#sku_csv'
  post '/check_sku', to: 'inventory_items#check_sku'
  get  'pages/index', to: 'pages#index'
  get '/login', to: 'sessions#login'
  get '/logout', to: 'sessions#logout'
  post '/confirm_login', to: 'sessions#confirm_login'
  post 'inventory_items/mass_action', to: 'inventory_items#mass_action'
  get 'inventory_items/destroy_all', :to => 'inventory_items#destroy_all'
  get 'inventory_items/soft_deleted', to: 'inventory_items#soft_deleted'
  post 'inventory_items/recover/:id', to: 'inventory_items#recover'
  post 'team_player_designs/mass_delete', to: 'team_player_designs#mass_delete'
  post 'team_players/mass_delete', to: 'team_players#mass_delete'
  post 'clothing/mass_toggle', to: 'clothing#mass_toggle'
  post 'accessory/mass_toggle', to: 'accessory#mass_toggle'

  resources :sales_channels
  resources :colors
  resources :teams do
    resources :team_players, only: :index
  end
  resources :team_players, only: [:show, :edit, :update, :destroy]
  resources :sizes
  resources :royalties
  resources :reserved_designs
  resources :team_player_designs
  resources :inventory_items do
    member do
      post 'recover'
    end
  end

  resources :clothing do
    get '/clothing_colors', to: 'clothing_colors#edit'
    put '/clothing_colors', to: 'clothing_colors#update'
    get '/clothing_sizes', to: 'clothing_sizes#edit'
    put '/clothing_sizes', to: 'clothing_sizes#update'
    post 'toggle_active', to: 'clothing#toggle_active'
    resources :tags
  end

  resources :accessory do
    get '/accessory_colors', to: 'accessory_colors#edit'
    put '/accessory_colors', to: 'accessory_colors#update'
    get '/accessory_sizes', to: 'accessory_sizes#edit'
    put '/accessory_sizes', to: 'accessory_sizes#update'
    post 'toggle_active', to: 'accessory#toggle_active'
    resources :tags
  end

  root to: 'sessions#login'
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :accessories
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :set_brand, only: [:show, :edit, :update, :destroy]

  # GET /brands
  # GET /brands.json
  def index
    @brands = Brand.all
  end

  # GET /brands/1
  # GET /brands/1.json
  def show
  end

  # GET /brands/new
  def new
    @brand = Brand.new
  end

  # GET /brands/1/edit
  def edit
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = Brand.new(brand_params)

    respond_to do |format|
      if @brand.save
        format.html { redirect_to @brand, notice: 'Brand was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /brands/1
  # PATCH/PUT /brands/1.json
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to @brand, notice: 'Brand was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand.destroy
    respond_to do |format|
      format.html { redirect_to brands_url, notice: 'Brand was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brand_params
      params.require(:brand).permit(:name, :sku)
    end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/brands/_form.html.slim
= form_for @brand do |f|
  - if @brand.errors.any?
    #error_explanation
      h2 = "#{pluralize(@brand.errors.count, "error")} prohibited this brand from being saved:"
      ul
        - @brand.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :sku
    = f.text_field :sku
  .actions = f.submit

app/views/brands/edit.html.slim
h1 Editing brand

== render 'form'

= link_to 'Show', @brand
'|
= link_to 'Back', brands_path

app/views/brands/index.html.slim
h1 Listing brands

table
  thead
    tr
      th Name
      th Sku
      th
      th
      th

  tbody
    - @brands.each do |brand|
      tr
        td = brand.name
        td = brand.sku
        td = link_to 'Show', brand
        td = link_to 'Edit', edit_brand_path(brand)
        td = link_to 'Destroy', brand, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Brand', new_brand_path

app/views/brands/new.html.slim
h1 New brand

== render 'form'

= link_to 'Back', brands_path

app/views/brands/show.html.slim
p#notice = notice

p
  strong Name:
  = @brand.name
p
  strong Sku:
  = @brand.sku

= link_to 'Edit', edit_brand_path(@brand)
'|
= link_to 'Back', brands_path